### ISSUE TITLE
Multiline comments: why /** ... **/ ?

### ISSUE THREAD

**Issue by eldyer** [a5huynh/vscode-ron#1]
Multiline comments are only highlighted when two asterisks are used, like this: /** ... **/.

/* ... */ isn't recognized, but seems correct according to the example in the ron github repo: https://github.com/ron-rs/ron

**Comment by a5huynh** [comment]
Hey @eldyer thanks for opening the issue. Definitely a bug in the grammar, I'll get a fix in asap!

**Comment by a5huynh** [comment]
@eldyer new version published.
