### ISSUE TITLE
VSCode not finding formatter for ron files

### ISSUE THREAD

**Issue by maxwell8888** [a5huynh/vscode-ron#16]
I've installed vscode-ron, restarted VSCode but still getting "There is no formatter for 'ron' files installed." for `test.ron` with `(player: (move_speed: 5))`. I'm not sure how to proceed from here so any guidance, eg for how to debug, would be appreciated.

**Comment by a5huynh** [comment]
Hey @maxwell8888, right now this extension is just for the syntax highlighting and doesn't support formatting the ron. Can you confirm that the syntax highlighting is working?

**Comment by maxwell8888** [comment]
Ah, sorry I should have read more carefully. See the syntax highlighting is working. Thanks
