### ISSUE TITLE
Single-Quoted Characters are not handled

### ISSUE THREAD

**Issue by aj-n** [a5huynh/vscode-ron#18]
Example:

![image](https://user-images.githubusercontent.com/7599165/214356001-c626868b-1d3e-4386-b34d-cf61b7bd5508.png)

I created a PR that adds simple `character` handling: <https://github.com/a5huynh/vscode-ron/pull/17>

PR Example with fix:

![image](https://user-images.githubusercontent.com/7599165/214356253-ebaa4deb-fdbc-4b0c-a389-eb6683f49ece.png)

**Comment by a5huynh** [comment]
Fixed w/ #17
