### ISSUE TITLE
Escaping character not supported

### ISSUE THREAD

**Issue by MaxenceDC** [a5huynh/vscode-ron#19]
Escaping a single quote ``"`` does nothing:

![image](https://github.com/a5huynh/vscode-ron/assets/77689281/f7d4842d-5b58-4ff8-9959-eacc964ccda3)

**Comment by a5huynh** [comment]
Thanks @xpe for reminding me about this issue 😅 . Your extension is probably more complete but I went ahead and fixed the issue in my grammar as well. 

@MaxenceDC, it should be updated in the latest version of the extension whenever your client updates it. Apologies for taking so long to fix it.
