### ISSUE TITLE
enormous memory usage upon installing

### ISSUE THREAD

**Issue by Maxgy** [a5huynh/vscode-ron#4]
When I first installed this extension I didn't realize, but eventually my computer was using 7 gb or ram instead of 1 to run VS Code. I didn't realize this extension was the issue until I installed it on a second machine and my memory usage instantly doubled.
OS: Arch Linux (both machines)

**Comment by a5huynh** [comment]
Hey @Maxgy, does this happen on a clean install w/ only this extension? I'll look into spinning up a VM w/ Arch to test this out later tonight.

**Comment by Maxgy** [comment]
@a5huynh Upon further research and experimentation, this is likely an issue with VS Code itself: [#82427](https://github.com/microsoft/vscode/issues/82427). I wouldn't worry too much about this extension, and for now I'll reinstall vscode-ron and use a workaround in VS Code.
