### ISSUE TITLE
How to toggle block comments?

### ISSUE THREAD

**Issue by Boscop** [a5huynh/vscode-ron#9]
Thanks for this great plugin :)
I usually use Sublime for everything but the lack of shortcuts to toggle comments is such a pain point that it's forcing me to VS Code for RON editing.
I found out that `Ctrl+/` works for toggling single line comments, but `Ctrl+Shift+/` doesn't work for toggling block comments. `Shift+Alt+A` doesn't work either.
What is the right shortcut for this?
If it's not implemented, could you please implement it? :)

**Comment by a5huynh** [comment]
@Boscop thanks for using the plugin! 

I'll take a look and update this issue. We might need to change the grammar a bit to specifically look for block comments

**Comment by Boscop** [comment]
Thanks for tackling this :)

**Comment by a5huynh** [comment]
@Boscop just pushed out a new version, let me know if the toggling works now!

**Comment by Boscop** [comment]
@a5huynh Thanks! Btw, I'm mostly using Sublime Text, could you maybe implement comment toggling for that, too? I'd already be super happy to have line-comment toggling with `Ctrl-/`.
(I would implement it myself but I don't know how to do that for Sublime Text.)
https://github.com/ron-rs/sublime-ron/blob/master/RON.sublime-syntax
